/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Extractor */

#ifndef _Included_Extractor
#define _Included_Extractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Extractor
 * Method:    sep_sum_circle
 * Signature: ([B[B[BIIIIIDDS[D[DDI[D[D[D[S)I
 */
JNIEXPORT jint JNICALL Java_Extractor_sep_1sum_1circle
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jdouble, jdouble, jshort, jdoubleArray, jdoubleArray, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jshortArray);

/*
 * Class:     Extractor
 * Method:    sep_sum_circann
 * Signature: ([B[B[BIIIIIDDS[D[DDDI[D[D[D[S)I
 */
JNIEXPORT jint JNICALL Java_Extractor_sep_1sum_1circann
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jdouble, jdouble, jshort, jdoubleArray, jdoubleArray, jdouble, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jshortArray);

/*
 * Class:     Extractor
 * Method:    sep_sum_ellipse
 * Signature: ([B[B[BIIIIIDDS[D[D[D[D[DDI[D[D[D[S)I
 */
JNIEXPORT jint JNICALL Java_Extractor_sep_1sum_1ellipse
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jdouble, jdouble, jshort, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jshortArray);

/*
 * Class:     Extractor
 * Method:    sep_sum_ellipann
 * Signature: ([B[B[BIIIIIDDS[D[D[D[D[DDDI[D[D[D[S)I
 */
JNIEXPORT jint JNICALL Java_Extractor_sep_1sum_1ellipann
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint, jint, jint, jdouble, jdouble, jshort, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jdouble, jint, jdoubleArray, jdoubleArray, jdoubleArray, jshortArray);

/*
 * Class:     Extractor
 * Method:    sep_extract
 * Signature: ([B[BIISIIFI[BIIIDZD[LSepobj;I)I
 */
JNIEXPORT jint JNICALL Java_Extractor_sep_1extract
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jshort, jint, jint, jfloat, jint, jbyteArray, jint, jint, jint, jdouble, jboolean, jdouble, jobjectArray, jint);

/*
 * Class:     Extractor
 * Method:    sep_kron_radius
 * Signature: ([B[BIIIID[D[D[D[D[D[D[D[S)V
 */
JNIEXPORT void JNICALL Java_Extractor_sep_1kron_1radius
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint, jdouble, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jshortArray);

/*
 * Class:     Extractor
 * Method:    sep_ellipse_coeffs
 * Signature: ([D[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_Extractor_sep_1ellipse_1coeffs
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     Extractor
 * Method:    sep_ellipse_axes
 * Signature: ([D[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_Extractor_sep_1ellipse_1axes
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
