/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Background_Sepbackmap */

#ifndef _Included_Background_Sepbackmap
#define _Included_Background_Sepbackmap
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
