/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Background_Sepobj */

#ifndef _Included_Background_Sepobj
#define _Included_Background_Sepobj
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
